### PR TITLE
Activity issue

### PR DESCRIPTION
**Pull request by johan-t**
Fix: #69 

The best Match now gets 24h to respond to the message if the best match does not write a message into the textChannel their match will be terminated and the user will get a new match, whilst the bestMatch will be deleted from the DB to prevent it from happening again.

### CODE REVIEW

**Comment by KoTenshi** [comment]
1. The 'bestMatchSentMessage' variable isn't user-specific meaning that matches would interfere with each other

2. using setTimeout doesn't work if the bot restarts

I have not tested if the code itself works but these are two issues i saw.

**Comment by TheLlamamarketer** [comment]
shouldn't we merge this branch into preproduction branch and not into main?

**Comment by johan-t** [comment]
> shouldn't we merge this branch into preproduction branch and not into main?

I think it is fine, we just need to remember to merge 'main' into 'development' before opening a new branch

**Comment by johan-t** [comment]
> 1. The 'bestMatchSentMessage' variable isn't user-specific meaning that matches would interfere with each other
> 2. using setTimeout doesn't work if the bot restarts
> 
> I have not tested if the code itself works but these are two issues i saw.

Good catch, I did not think about this will fix

**Review by TheLlamamarketer — APPROVED** [review]

**Pull request merged**
