### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by johan-t**
Changed the documentation to include new setup 

Fix: #40

### CODE REVIEW

**Comment by TheLlamamarketer** [comment]
looks good, I dont think there is anything else needed to add

**Comment by GregTCLTK** [comment]
> looks good, I dont think there is anything else needed to add

Why did you close it then lol?

**Comment by TheLlamamarketer** [comment]
> > looks good, I dont think there is anything else needed to add
> 
> Why did you close it then lol?

I thought that's what we need to do with these pull requests?

**Comment by GregTCLTK** [comment]
Nah, we need to merge them first.

**Comment by TheLlamamarketer** [comment]
oh i didnt merge, I see now

**Review by TheLlamamarketer — APPROVED** [review]

**Pull request merged**
