### PR TITLE
Issue 54

### LINKED ISSUE #54: Prevent two users beeing matched twice
If you take the test multiple times the possibility for being matched with the same person over and over is very high, which is not ideal for diverse user interaction.

### PR DESCRIPTION
**Pull request by johan-t**
# What Issue did you fix?
Fixes: #54 

# Quick description of your approach:
This is a follow up to @q-Sci PR. When finding a match it will go through all of the conversations for that user and skip the users as BestMatch that the user has had a conversation with before. 
Also instead of calling sendQuestion it calls intiateConversation and calls sendQuestion when the test is not complete.

## Checklist before requesting a review:
- [x] I have removed the comments fron the questions
- [x] I have added comments to my code, particularly in hard-to-understand areas
- [x] I have removed all of the debugging 'console.logs'
- [x] I have ensured that all of my variables, functions, etc. are named sensibly (Are able to be understood by someone who has not seen my code before)
- [x] I have read through my changes to make sure that I did not change anything that was not related to the issue I am fixing

### CODE REVIEW

**Comment by johan-t** [comment]
Also I changed question.json to questions.ts, because json does not allow comments

**Comment by q-Sci** [comment]
The initial use of the `/match` command (before taking the test) returns some error:

```
TypeError: text.split is not a function
    at decrypt (/home/qsci/Projects/ContraBot/encryptionUtils.ts:18:28)
    at executeMatch (/home/qsci/Projects/ContraBot/commands/match-command.ts:11:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (/home/qsci/Projects/ContraBot/index.ts:58:17)
TypeError: text.split is not a function
    at decrypt (/home/qsci/Projects/ContraBot/encryptionUtils.ts:18:28)
    at executeMatch (/home/qsci/Projects/ContraBot/commands/match-command.ts:11:71)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Client.<anonymous> (/home/qsci/Projects/ContraBot/index.ts:58:17)
```

**Comment by q-Sci** [comment]
Also I cant't test it completely now because all the old db entries are invalid or something: `Skipped: userVector for userId <user-id> is not a string`.

**Comment by johan-t** [comment]
> Also I cant't test it completely now because all the old db entries are invalid or something: `Skipped: userVector for userId <user-id> is not a string`.

You can create new entries

**Pull request closed without merging**
